### ISSUE TITLE
1.16.5?

### ISSUE THREAD

**Issue by CatastropheChou** [AbdElAziz333/Pluto#11]
[KryptonReforged](https://github.com/TeamDeusVult/KryptonReforged) has a [critical bug](https://github.com/TeamDeusVult/KryptonReforged/issues/7) and it seems that its authors abandoned it, so I don't wanna use KryptonReforged.
It would be nice if you can do that.

**Comment by AbdElAziz333** [comment]
1.16.5 is OUTDATED, and i never planned for that, and Pluto focuses in the modern versions of Minecraft which is 1.18, 1.19, 1.20, + etc.
