### ISSUE TITLE
Typo on Pluto's CurseForge page.

### ISSUE THREAD

**Issue by AnAwesomGuy** [AbdElAziz333/Pluto#16]
The CurseForge page for Pluto has a _minor_ typo. This isn't really anything important, but I'm still reporting it because why not?
![image](https://user-images.githubusercontent.com/79700396/218041992-38211796-eaa6-4ba9-bc7c-891b003ac869.png)
Seen is misspelled into sen.

**Comment by VirtualEagle04** [comment]
Bruh
