### ISSUE TITLE
Causes Visual Issues on Server

### ISSUE THREAD

**Issue by GordonRamsay20** [AbdElAziz333/Pluto#22]
1.18.2 Not able to see my hand or the item I'm holding, and I can't see certain modded things like items on shelves from another furniture or knives on cutting boards from farmer's delight, ars nouveau mage lights, and so on. The items are there, I just can't see them. I don't know if It's an issue with the mod or an incompatibility. I know pluto's new update is causing it because this only occurred with the 0.0.6 update. Here's the server log 
[latest.log](https://github.com/AbdElAziz333/Pluto/files/11132430/latest.log)

**Comment by GordonRamsay20** [comment]
The problem magically disappeared/stopped happening

**Comment by AbdElAziz333** [comment]
for more help, this issue may be from Radium or Rubidium because both have similar issues to your issue, so try to remove/change them. Good Luck!
