### ISSUE TITLE
flashing particles through wall/cave

### ISSUE THREAD

**Issue by Totomio** [AbdElAziz333/Pluto#28]
Forge 43.2.13, Minecraft 1.19.2, Rubidium, Oculus.

How to reproduce this issue  :
Mine 6 blocks under the surface, active /weather rain, back survival mode, mine blocks above you and each time you pick up a block, rain particles flash through the walls/sone/blocks, occur also with torch lights, smoke.
The issue only occur while shaders are activated.
Desactivating this mod solve the problem.

Help.

**Comment by KarinMiku** [comment]
Indeed, there is some kind of incompat between pluto and rubidium / oculus, this bug can happen while picking up items, and im playing on 1.18.2 - forge 40.2.0. Seems like it is something that can happen in all versions

**Comment by AbdElAziz333** [comment]
Pluto doesn't touch the rendering behaviors, this issue is from Oculus.
