### ISSUE TITLE
[Improvement] Even better compatibility with Canary. (1.18.2)

### ISSUE THREAD

**Issue by StormDragon-64** [AbdElAziz333/Pluto#3]
This happens with krypton reforged, not just Pluto, but mixins from pluto and canary conflict with each other, so neither optimization is used. Maybe make one of the mixins disable automatically if the other mod is detected? I don't know which optimization is better, so you choose which mixin to disable from either mod. Here is a screenshot of the logs saying there is a mixin conflict: 
![image](https://user-images.githubusercontent.com/80718549/197445602-a30931be-adba-4eed-9ec5-3d483e22fac6.png)

**Comment by AbdElAziz333** [comment]
oh, i forgot adding the properties file, i will add a fix soon.

**Comment by AbdElAziz333** [comment]
could you test this release ?
https://github.com/AbdElAziz333/Pluto/releases/tag/mc1.18.2-v0.0.2

**Comment by StormDragon-64** [comment]
It seems to work fine, I ran my server for a while and played on it with multiple people on my 200 mod modpack, and there were no issues.

**Comment by AbdElAziz333** [comment]
then the issue is fixed, good luck!
