### ISSUE TITLE
crashes at startup 1.19.2

### ISSUE THREAD

**Issue by papillo12** [AbdElAziz333/Pluto#4]
after testing with several mods, I found that pluto in the latest version crashes when opening the game, I had to downgrade to fix it.
[crash-2022-10-25_08.24.32-client.txt](https://github.com/AbdElAziz333/Pluto/files/9861170/crash-2022-10-25_08.24.32-client.txt)
[crash-2022-10-25_08.23.15-client.txt](https://github.com/AbdElAziz333/Pluto/files/9861171/crash-2022-10-25_08.23.15-client.txt)
[crash-2022-10-25_08.21.32-client.txt](https://github.com/AbdElAziz333/Pluto/files/9861172/crash-2022-10-25_08.21.32-client.txt)
[crash-2022-10-25_08.19.10-client.txt](https://github.com/AbdElAziz333/Pluto/files/9861173/crash-2022-10-25_08.19.10-client.txt)
[crash-2022-10-25_08.26.26-client.txt](https://github.com/AbdElAziz333/Pluto/files/9861174/crash-2022-10-25_08.26.26-client.txt)
[latest.log](https://github.com/AbdElAziz333/Pluto/files/9861178/latest.log)

**Comment by papillo12** [comment]
Yes, I'm sure

**Comment by papillo12** [comment]
I put pluto back in the latest version and the game crashed again

[crash-2022-10-25_09.42.06-client.txt](https://github.com/AbdElAziz333/Pluto/files/9861847/crash-2022-10-25_09.42.06-client.txt)
[latest.log](https://github.com/AbdElAziz333/Pluto/files/9861849/latest.log)

**Comment by AbdElAziz333** [comment]
could you test 0.0.5 update?

**Comment by papillo12** [comment]
now working fine, thanks

**Comment by AbdElAziz333** [comment]
I hope you have a good day!
